SELECT  CUSTDES AS 'Customer',
ORDERS.ORDNAME AS 'Order',
 dbo.fnFormatDate(dbo.MINTODATE(ORDERS.CURDATE), 'DD/MM/YY') AS 'Date',
 PART.PARTNAME AS 'Part Number',
 PART.PARTDES AS 'Part Description',
 dbo.fnFormatDate(dbo.MINTODATE(ORDERITEMS.DUEDATE), 'DD/MM/YY') AS 'Due Date',
 (ORDERITEMS.TQUANT)/1000 AS 'Ordered Qty',
(ORDERITEMS.TBALANCE)/1000 AS 'Balance',
 (TRANSORDER.TQUANT)/1000 AS 'Transaction Quantity',
 CASE WHEN TRANSORDER.TYPE = 'X' THEN INVOICES.IVNUM
 WHEN TRANSORDER.TYPE = 'V' THEN INVOICES.IVNUM
ELSE
	DOCUMENTS.DOCNO
END,
 dbo.fnFormatDate(dbo.MINTODATE(TRANSORDER.CURDATE), 'DD/MM/YY') AS 'Date',
 CASE WHEN TRANSORDER.CURDATE = 0 THEN ''
ELSE  dbo.fnFormatDate(dbo.MINTODATE(ORDERITEMS.DUEDATE - TRANSORDER.CURDATE), 'DD/MM/YY') 
END
FROM ORDERS
JOIN ORDERITEMS on ORDERS.ORD = ORDERITEMS.ORD
JOIN CUSTOMERS on CUSTOMERS.CUST = ORDERS.CUST
JOIN PART on ORDERITEMS.PART = PART.PART
JOIN PARTPARAM on PART.PART = PARTPARAM.PART
JOIN ORDSTATUS on ORDERS.ORDSTATUS = ORDSTATUS.ORDSTATUS
RIGHT OUTER JOIN TRANSORDER on ORDERITEMS.ORDI = TRANSORDER.ORDI
RIGHT OUTER JOIN DOCUMENTS on DOCUMENTS.DOC = TRANSORDER.DOC  and TRANSORDER.TYPE = 'X' or TRANSORDER.TYPE = 'Y'
RIGHT OUTER JOIN INVOICES on INVOICES.IV = TRANSORDER.DOC and TRANSORDER.TYPE = 'X' or TRANSORDER.TYPE = 'V'
RIGHT OUTER JOIN DOCTYPES on TRANSORDER.TYPE = DOCTYPES.TYPE 
WHERE PARTPARAM.INVFLAG  = 'Y'
AND ORDSTATUS.MANAGERREPOUT  <> 'Y'
AND ORDERS.FORECASTFLAG  <> 'S'
AND ORDERS.FORECASTFLAG <> 'F'
AND DOCTYPES.OTYPE  <> 'P'
AND TRANSORDER.TYPE NOT IN ('F', 'I', 'J', 'K', 'P', 'W', 'Y', 'L')
AND ORDERITEMS.ORD  <> 0
AND DOCUMENTS.TYPE  <> 'A'
AND TRANSORDER.TQUANT  <> 0
AND  dbo.MINTODATE(ORDERITEMS.DUEDATE) BETWEEN DATEADD(day, -14, GETDATE()) AND GETDATE()
